agenda/config/routes.rb
Agenda::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :contatos

root :to => 'contatos#index'

end

agenda/app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

agenda/app/models/contato.rb
class Contato < ActiveRecord::Base
	validates_presence_of :nome, :message => "Eh necessario"
	validates_length_of :nome , :maximum => 3, :message => "Precisa ter no maximo 3"

	has_many :endereco
	accepts_nested_attributes_for :endereco

end

agenda/app/models/endereco.rb
class Endereco < ActiveRecord::Base
	has_one :contato
end

agenda/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

agenda/app/controllers/contatos_controller.rb
class ContatosController < ApplicationController
  # GET /contatos
  # GET /contatos.json
  def index
    @contatos = Contato.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contatos }
    end
  end

  # GET /contatos/1
  # GET /contatos/1.json
  def show
    @contato = Contato.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contato }
    end
  end

  # GET /contatos/new
  # GET /contatos/new.json
  def new
    @contato = Contato.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contato }
    end
  end

  # GET /contatos/1/edit
  def edit
    @contato = Contato.find(params[:id])
  end

  # POST /contatos
  # POST /contatos.json
  def create
    @contato = Contato.new(params[:contato])
    @contato.endereco = Endereco.new(params[:endereco])


    respond_to do |format|
      if @contato.save
        format.html { redirect_to @contato, notice: 'Contato was successfully created.' }
        format.json { render json: @contato, status: :created, location: @contato }
      else
        format.html { render action: "new" }
        format.json { render json: @contato.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contatos/1
  # PUT /contatos/1.json
  def update
    @contato = Contato.find(params[:id])

    respond_to do |format|
      if @contato.update_attributes(params[:contato])
        format.html { redirect_to @contato, notice: 'Contato was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @contato.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contatos/1
  # DELETE /contatos/1.json
  def destroy
    @contato = Contato.find(params[:id])
    @contato.destroy

    respond_to do |format|
      format.html { redirect_to contatos_url }
      format.json { head :ok }
    end
  end
end

agenda/app/helpers/application_helper.rb
module ApplicationHelper
end

agenda/app/helpers/contatos_helper.rb
module ContatosHelper
end

agenda/app/views/contatos/_form.html.erb
<%= form_for(@contato) do |f| %>
  <% if @contato.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contato.errors.count, "error") %> houve um erro e este contato nao pode ser salvo:</h2>

      <ul>
      <% @contato.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :telefone %><br />
    <%= f.text_field :telefone %>
  </div>
  <%= f.fields_for :endereco do |endereco_fields| %>
    <div class="field">
      <%= endereco_fields.label :nome %><br />
      <%= endereco_fields.text_field :nome %>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit  %>
  </div>
<% end %>

agenda/app/views/contatos/edit.html.erb
<h1>Editing contato</h1>

<%= render 'form' %>

<%= link_to 'Show', @contato %> |
<%= link_to 'Back', contatos_path %>

agenda/app/views/contatos/index.html.erb
<h1>Listing contatos</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Telefone</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contatos.each do |contato| %>
  <tr>
    <td><%= contato.nome %></td>
    <td><%= contato.telefone %></td>
    <td><%= link_to 'Show', contato %></td>
    <td><%= link_to 'Edit', edit_contato_path(contato) %></td>
    <td><%= link_to 'Destroy', contato, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Contato', new_contato_path %>

agenda/app/views/contatos/new.html.erb
<h1>New contato</h1>

<%= render 'form' %>

<%= link_to 'Back', contatos_path %>

agenda/app/views/contatos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @contato.nome %>
</p>

<p>
  <b>Telefone:</b>
  <%= @contato.telefone %>
</p>


<%= link_to 'Edit', edit_contato_path(@contato) %> |
<%= link_to 'Back', contatos_path %>

agenda/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Agenda</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>